### ISSUE TITLE
u-picker 在微信小程序的报错信息

### ISSUE THREAD

**Issue by mchuangzhong** [YanxinNet/uView#520]
![image](https://user-images.githubusercontent.com/6203807/95560412-d6f2e680-0a4b-11eb-86cc-9d1aeb1c4770.png)

**Comment by mchuangzhong** [comment]
VM13:1 [Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'map' of undefined"

found in

---> <UPicker> at node_modules/uview-ui/components/u-picker/u-picker.vue
       pages/user/userinfo.vue
console.error @ VM13:1
warn @ vendor.js:3141
Vue.config.errorHandler @ vendor.js:8330
globalHandleError @ vendor.js:4402
handleError @ vendor.js:4371
invokeWithErrorHandling @ vendor.js:4394
Vue.__call_hook @ vendor.js:8387
_vue.default.__call_hook @ vendor.js:1519
ready @ vendor.js:1624
r.safeCallback @ VM21 WAService.js:2
r.call @ VM21 WAService.js:2
M.triggerLifeTime @ VM21 WAService.js:2
(anonymous) @ VM21 WAService.js:2
r.safeCallback @ VM21 WAService.js:2
value @ VM21 WAService.js:2
(anonymous) @ VM21 WAService.js:2
r @ VM21 WAService.js:2
(anonymous) @ VM21 WAService.js:2
(anonymous) @ VM21 WAService.js:2
i @ VM19 asdebug.js:1
c @ VM19 asdebug.js:1
(anonymous) @ VM19 asdebug.js:1
p @ VM19 asdebug.js:1
f @ VM19 asdebug.js:1
(anonymous) @ VM19 asdebug.js:1
_ws.onmessage @ VM19 asdebug.js:1
VM13:1 TypeError: Cannot read property 'map' of undefined
    at VueComponent.setCitys (u-picker.js:746)
    at VueComponent.init (u-picker.js:663)
    at VueComponent.mounted (u-picker.js:530)
    at invokeWithErrorHandling (vendor.js:4386)
    at VueComponent.Vue.__call_hook (vendor.js:8387)
    at VueComponent._vue.default.__call_hook (vendor.js:1519)
    at Xe.ready (vendor.js:1624)
    at r.safeCallback (VM21 WAService.js:2)
    at r.call (VM21 WAService.js:2)
    at n.M.triggerLifeTime (VM21 WAService.js:2)
console.error @ VM13:1
Vue.config.errorHandler @ vendor.js:8331
globalHandleError @ vendor.js:4402
handleError @ vendor.js:4371
invokeWithErrorHandling @ vendor.js:4394
Vue.__call_hook @ vendor.js:8387
_vue.default.__call_hook @ vendor.js:1519
ready @ vendor.js:1624
r.safeCallback @ VM21 WAService.js:2
r.call @ VM21 WAService.js:2
M.triggerLifeTime @ VM21 WAService.js:2
(anonymous) @ VM21 WAService.js:2
r.safeCallback @ VM21 WAService.js:2
value @ VM21 WAService.js:2
(anonymous) @ VM21 WAService.js:2
r @ VM21 WAService.js:2
(anonymous) @ VM21 WAService.js:2
(anonymous) @ VM21 WAService.js:2
i @ VM19 asdebug.js:1
c @ VM19 asdebug.js:1
(anonymous) @ VM19 asdebug.js:1
p @ VM19 asdebug.js:1
f @ VM19 asdebug.js:1
(anonymous) @ VM19 asdebug.js:1
_ws.onmessage @ VM19 asdebug.js:1
VM13:1 [Vue warn]: Error in callback for watcher "regionChange": "TypeError: Cannot read property '0' of undefined"

found in

---> <UPicker> at node_modules/uview-ui/components/u-picker/u-picker.vue
       pages/user/userinfo.vue
console.error @ VM13:1
warn @ vendor.js:3141
Vue.config.errorHandler @ vendor.js:8330
globalHandleError @ vendor.js:4402
handleError @ vendor.js:4371
run @ vendor.js:7029
flushSchedulerQueue @ vendor.js:6769
(anonymous) @ vendor.js:4508
flushCallbacks @ vendor.js:4436
Promise.then (async)
timerFunc @ vendor.js:4463
nextTick @ vendor.js:4518
queueWatcher @ vendor.js:6861
update @ vendor.js:7003
notify @ vendor.js:3255
reactiveSetter @ vendor.js:3589
proxySetter @ vendor.js:7090
init @ u-picker.js:628
mounted @ u-picker.js:530
invokeWithErrorHandling @ vendor.js:4386
Vue.__call_hook @ vendor.js:8387
_vue.default.__call_hook @ vendor.js:1519
ready @ vendor.js:1624
r.safeCallback @ VM21 WAService.js:2
r.call @ VM21 WAService.js:2
M.triggerLifeTime @ VM21 WAService.js:2
(anonymous) @ VM21 WAService.js:2
r.safeCallback @ VM21 WAService.js:2
value @ VM21 WAService.js:2
(anonymous) @ VM21 WAService.js:2
r @ VM21 WAService.js:2
(anonymous) @ VM21 WAService.js:2
(anonymous) @ VM21 WAService.js:2
i @ VM19 asdebug.js:1
c @ VM19 asdebug.js:1
(anonymous) @ VM19 asdebug.js:1
p @ VM19 asdebug.js:1
f @ VM19 asdebug.js:1
(anonymous) @ VM19 asdebug.js:1
_ws.onmessage @ VM19 asdebug.js:1
VM13:1 TypeError: Cannot read property '0' of undefined
    at VueComponent.regionChange (u-picker.js:557)
    at Watcher.run (vendor.js:7027)
    at flushSchedulerQueue (vendor.js:6769)
    at Array.<anonymous> (vendor.js:4508)
    at flushCallbacks (vendor.js:4436)
console.error @ VM13:1
Vue.config.errorHandler @ vendor.js:8331
globalHandleError @ vendor.js:4402
handleError @ vendor.js:4371
run @ vendor.js:7029
flushSchedulerQueue @ vendor.js:6769
(anonymous) @ vendor.js:4508
flushCallbacks @ vendor.js:4436
Promise.then (async)
timerFunc @ vendor.js:4463
nextTick @ vendor.js:4518
queueWatcher @ vendor.js:6861
update @ vendor.js:7003
notify @ vendor.js:3255
reactiveSetter @ vendor.js:3589
proxySetter @ vendor.js:7090
init @ u-picker.js:628
mounted @ u-picker.js:530
invokeWithErrorHandling @ vendor.js:4386
Vue.__call_hook @ vendor.js:8387
_vue.default.__call_hook @ vendor.js:1519
ready @ vendor.js:1624
r.safeCallback @ VM21 WAService.js:2
r.call @ VM21 WAService.js:2
M.triggerLifeTime @ VM21 WAService.js:2
(anonymous) @ VM21 WAService.js:2
r.safeCallback @ VM21 WAService.js:2
value @ VM21 WAService.js:2
(anonymous) @ VM21 WAService.js:2
r @ VM21 WAService.js:2
(anonymous) @ VM21 WAService.js:2
(anonymous) @ VM21 WAService.js:2
i @ VM19 asdebug.js:1
c @ VM19 asdebug.js:1
(anonymous) @ VM19 asdebug.js:1
p @ VM19 asdebug.js:1
f @ VM19 asdebug.js:1
(anonymous) @ VM19 asdebug.js:1
_ws.onmessage @ VM19 asdebug.js:1
VM13:1 MiniProgramError
Cannot read property 'map' of undefined
TypeError: Cannot read property 'map' of undefined
    at VueComponent.setCitys (http://127.0.0.1:52117/appservice/node-modules/uview-ui/components/u-picker/u-picker.js:635:40)
    at VueComponent.init (http://127.0.0.1:52117/appservice/node-modules/uview-ui/components/u-picker/u-picker.js:557:20)
    at Function.<anonymous> (http://127.0.0.1:52117/appservice/node-modules/uview-ui/components/u-picker/u-picker.js:464:29)
    at <setTimeout callback function>
    at http://127.0.0.1:52117/appservice/__dev__/WAService.js:2:121816
    at http://127.0.0.1:52117/appservice/__dev__/WAService.js:2:113742
